const LESSON_UPLOAD_LOADING = 'LESSON_UPLOAD_LOADING';
const LESSON_UPLOAD_LOADED = 'LESSON_UPLOAD_LOADED';
const LESSON_UPLOAD_ERROR = 'LESSON_UPLOAD_ERROR';
const CLEAR_LESSON = 'CLEAR_LESSON';

const SEGMENTS_LOADING = 'SEGMENTS_LOADING';
const SEGMENTS_LOADED = 'SEGMENTS_LOADED';
const SEGMENTS_ERROR = 'SEGMENTS_ERROR';

const LessonActionTypes = {
	LESSON_UPLOAD_LOADING,
	LESSON_UPLOAD_LOADED,
	LESSON_UPLOAD_ERROR,
	CLEAR_LESSON,
	SEGMENTS_LOADING,
	SEGMENTS_LOADED,
	SEGMENTS_ERROR,
} as const;

export default LessonActionTypes;