const LESSON_UPLOAD_LOADING = 'LESSON_UPLOAD_LOADING';
const LESSON_UPLOAD_LOADED = 'LESSON_UPLOAD_LOADED';
const LESSON_UPLOAD_ERROR = 'LESSON_UPLOAD_ERROR';
const CLEAR_LESSON = 'CLEAR_LESSON';

const LessonActionTypes = {
	LESSON_UPLOAD_LOADING,
	LESSON_UPLOAD_LOADED,
	LESSON_UPLOAD_ERROR,
	CLEAR_LESSON,
} as const;

export default LessonActionTypes;
