const VIDEO_UPLOAD_LOADING = 'VIDEO_UPLOAD_LOADING';
const VIDEO_UPLOAD_LOADED = 'VIDEO_UPLOAD_LOADED';
const VIDEO_UPLOAD_ERROR = 'VIDEO_UPLOAD_ERROR';
const CLEAR_VIDEO = 'CLEAR_VIDEO';

const VideoActionTypes = {
	VIDEO_UPLOAD_LOADING,
	VIDEO_UPLOAD_LOADED,
	VIDEO_UPLOAD_ERROR,
	CLEAR_VIDEO,
} as const;

export default VideoActionTypes;
